[Mon Sep 03 06:25:01.860873 2018] [wsgi:warn] [pid 1394:tid 140562567169920] mod_wsgi: Compiled for Python/3.5.1+.
[Mon Sep 03 06:25:01.860896 2018] [wsgi:warn] [pid 1394:tid 140562567169920] mod_wsgi: Runtime using Python/3.5.2.
[Mon Sep 03 06:25:01.860931 2018] [mpm_event:notice] [pid 1394:tid 140562567169920] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/3.5.2 configured -- resuming normal operations
[Mon Sep 03 06:25:01.860936 2018] [core:notice] [pid 1394:tid 140562567169920] AH00094: Command line: '/usr/sbin/apache2'
[Mon Sep 03 06:25:06.148354 2018] [wsgi:error] [pid 11015:tid 140562458699520] Running with :project.server.config.DevelopmentConfig
[Mon Sep 03 06:25:07.131815 2018] [wsgi:error] [pid 11015:tid 140562458699520] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:25:07.131844 2018] [wsgi:error] [pid 11015:tid 140562458699520]   """)
[Mon Sep 03 06:25:09.098806 2018] [wsgi:error] [pid 11015:tid 140562416736000] Using conig: server.config.DevelopmentConfig
[Mon Sep 03 06:25:09.752707 2018] [wsgi:error] [pid 11015:tid 140562450306816] Using congig: project.config.DevelopmentConfig
[Mon Sep 03 06:25:10.197600 2018] [wsgi:error] [pid 11015:tid 140562450306816] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:25:10.197631 2018] [wsgi:error] [pid 11015:tid 140562450306816]   """)
[Mon Sep 03 06:25:10.535844 2018] [wsgi:error] [pid 11015:tid 140562433521408] Using config: server.config.DevelopmentConfig
[Mon Sep 03 06:25:11.140624 2018] [wsgi:error] [pid 11015:tid 140562425128704] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:25:11.140653 2018] [wsgi:error] [pid 11015:tid 140562425128704]   """)
[Mon Sep 03 06:25:11.640582 2018] [wsgi:error] [pid 11015:tid 140562334217984] Using config: project.config.DevelopmentConfig
[Mon Sep 03 06:25:11.901734 2018] [wsgi:error] [pid 11015:tid 140562334217984] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:25:11.901756 2018] [wsgi:error] [pid 11015:tid 140562334217984]   """)
[Mon Sep 03 06:25:12.161599 2018] [wsgi:error] [pid 11015:tid 140562258683648] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:25:12.161615 2018] [wsgi:error] [pid 11015:tid 140562258683648]   """)
[Mon Sep 03 06:25:12.169777 2018] [wsgi:error] [pid 11015:tid 140562275469056] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:25:12.169795 2018] [wsgi:error] [pid 11015:tid 140562275469056]   """)
[Mon Sep 03 06:25:12.866314 2018] [wsgi:error] [pid 11015:tid 140562208327424] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:25:12.866338 2018] [wsgi:error] [pid 11015:tid 140562208327424]   """)
[Mon Sep 03 06:25:12.871073 2018] [wsgi:error] [pid 11015:tid 140562208327424] Using config: api.config.DevConfig
[Mon Sep 03 06:25:21.426570 2018] [wsgi:error] [pid 11016:tid 140562433521408] Using conig: server.config.DevelopmentConfig
[Mon Sep 03 06:25:22.111712 2018] [wsgi:error] [pid 11016:tid 140562425128704] Using congig: project.config.DevelopmentConfig
[Mon Sep 03 06:25:22.519397 2018] [wsgi:error] [pid 11016:tid 140562425128704] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:25:22.519412 2018] [wsgi:error] [pid 11016:tid 140562425128704]   """)
[Mon Sep 03 06:25:22.999499 2018] [wsgi:error] [pid 11016:tid 140562416736000] Using config: server.config.DevelopmentConfig
[Mon Sep 03 06:25:23.431903 2018] [wsgi:error] [pid 11016:tid 140562441914112] Using config: project.config.DevelopmentConfig
[Mon Sep 03 06:25:23.558975 2018] [wsgi:error] [pid 11016:tid 140562441914112] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:25:23.558996 2018] [wsgi:error] [pid 11016:tid 140562441914112]   """)
[Mon Sep 03 06:25:23.598587 2018] [wsgi:error] [pid 11016:tid 140562458699520] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:25:23.598610 2018] [wsgi:error] [pid 11016:tid 140562458699520]   """)
[Mon Sep 03 06:25:24.294133 2018] [wsgi:error] [pid 11016:tid 140562334217984] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:25:24.294164 2018] [wsgi:error] [pid 11016:tid 140562334217984]   """)
[Mon Sep 03 06:25:24.299761 2018] [wsgi:error] [pid 11016:tid 140562334217984] Using config: api.config.DevConfig
[Mon Sep 03 06:25:46.396139 2018] [wsgi:error] [pid 11016:tid 140562267076352] Running with :project.server.config.DevelopmentConfig
[Mon Sep 03 06:25:46.671415 2018] [wsgi:error] [pid 11016:tid 140562267076352] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:25:46.671438 2018] [wsgi:error] [pid 11016:tid 140562267076352]   """)
[Mon Sep 03 06:28:11.969613 2018] [wsgi:error] [pid 11015:tid 140562183149312] Using config: api.config.DevelopmentConfig
[Mon Sep 03 06:28:12.046921 2018] [wsgi:error] [pid 11016:tid 140562241898240] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:28:12.046951 2018] [wsgi:error] [pid 11016:tid 140562241898240]   """)
[Mon Sep 03 06:28:12.283844 2018] [wsgi:error] [pid 11015:tid 140562425128704] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:28:12.283859 2018] [wsgi:error] [pid 11015:tid 140562425128704]   """)
[Mon Sep 03 06:28:13.161210 2018] [wsgi:error] [pid 11016:tid 140562225112832] wsdlpath /usr/local/lib/python3.5/dist-packages/confirmit-0.1-py3.5.egg/confirmit
[Mon Sep 03 06:28:15.552182 2018] [wsgi:error] [pid 11016:tid 140562225112832] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:28:15.552213 2018] [wsgi:error] [pid 11016:tid 140562225112832]   """)
[Mon Sep 03 06:29:12.276199 2018] [wsgi:error] [pid 11015:tid 140562225112832] wsdlpath /usr/local/lib/python3.5/dist-packages/confirmit-0.1-py3.5.egg/confirmit
[Mon Sep 03 06:29:14.493161 2018] [wsgi:error] [pid 11015:tid 140562225112832] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:29:14.493192 2018] [wsgi:error] [pid 11015:tid 140562225112832]   """)
[Mon Sep 03 06:33:15.107392 2018] [wsgi:error] [pid 11015:tid 140562267076352] Using config: project.config.DevelopmentConfig
[Mon Sep 03 06:33:15.476639 2018] [wsgi:error] [pid 11015:tid 140562267076352] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:33:15.476661 2018] [wsgi:error] [pid 11015:tid 140562267076352]   """)
[Mon Sep 03 06:35:37.978421 2018] [wsgi:error] [pid 11016:tid 140562325825280] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:35:37.978444 2018] [wsgi:error] [pid 11016:tid 140562325825280]   """)
[Mon Sep 03 06:37:26.900566 2018] [wsgi:error] [pid 11016:tid 140562300647168] Using config: project.config.DevelopmentConfig
[Mon Sep 03 06:37:27.466084 2018] [wsgi:error] [pid 11016:tid 140562300647168] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:37:27.466124 2018] [wsgi:error] [pid 11016:tid 140562300647168]   """)
[Mon Sep 03 06:37:27.731857 2018] [wsgi:error] [pid 11016:tid 140562283861760] Using config: api.config.DevelopmentConfig
[Mon Sep 03 06:37:27.959244 2018] [wsgi:error] [pid 11016:tid 140562258683648] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:37:27.959266 2018] [wsgi:error] [pid 11016:tid 140562258683648]   """)
[Mon Sep 03 06:37:44.817770 2018] [wsgi:error] [pid 11015:tid 140562275469056] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 06:37:44.817803 2018] [wsgi:error] [pid 11015:tid 140562275469056]   """)
[Mon Sep 03 06:37:45.262359 2018] [wsgi:error] [pid 11015:tid 140562334217984] refsdffdsfsfdfsdf beyond@humaniti.com None None
[Mon Sep 03 06:37:46.959009 2018] [wsgi:error] [pid 11015:tid 140562334217984] test ytyrtyr&nbsp
[Mon Sep 03 06:37:46.959046 2018] [wsgi:error] [pid 11015:tid 140562334217984] ram.gonuguntla@gmail.com
[Mon Sep 03 06:37:46.959053 2018] [wsgi:error] [pid 11015:tid 140562334217984] 
[Mon Sep 03 06:37:46.959059 2018] [wsgi:error] [pid 11015:tid 140562334217984] Email sent! Message ID:
[Mon Sep 03 06:37:46.959064 2018] [wsgi:error] [pid 11015:tid 140562334217984] 010201659e26c986-887fb30d-dc74-4a92-a727-00896c64925e-000000
[Mon Sep 03 07:18:01.245371 2018] [wsgi:error] [pid 11015:tid 140562309039872] [client 203.145.182.245:65147] mod_wsgi (pid=11015): Exception occurred processing WSGI script '/home/puneet/release_2/humaniti/humaniti/settings/api/settings.wsgi'., referer: http://localhost:4200/userSettings/profile
[Mon Sep 03 07:18:01.245528 2018] [wsgi:error] [pid 11015:tid 140562309039872] [client 203.145.182.245:65147] OSError: failed to write data, referer: http://localhost:4200/userSettings/profile
[Mon Sep 03 09:27:31.483207 2018] [wsgi:error] [pid 11015:tid 140562241898240] ERROR:project.views:(psycopg2.IntegrityError) duplicate key value violates unique constraint "user_property_uc"
[Mon Sep 03 09:27:31.483240 2018] [wsgi:error] [pid 11015:tid 140562241898240] DETAIL:  Key (user_id, address)=(43, ssss) already exists.
[Mon Sep 03 09:27:31.483246 2018] [wsgi:error] [pid 11015:tid 140562241898240]  [SQL: 'INSERT INTO property (user_id, is_ownership, is_rent, rent_amount, property_id, address, property_type, bedrooms, carparks, bathrooms, landarea, estimated_value, financial_account_id, reported_value, existing_property, use_estimate, provider_id, is_moneysoft, created_at, updated_at) VALUES (%(user_id)s, %(is_ownership)s, %(is_rent)s, %(rent_amount)s, %(property_id)s, %(address)s, %(property_type)s, %(bedrooms)s, %(carparks)s, %(bathrooms)s, %(landarea)s, %(estimated_value)s, %(financial_account_id)s, %(reported_value)s, %(existing_property)s, %(use_estimate)s, %(provider_id)s, %(is_moneysoft)s, %(created_at)s, %(updated_at)s) RETURNING property.id'] [parameters: {'rent_amount': 0, 'bedrooms': 0, 'created_at': datetime.datetime(2018, 9, 3, 9, 27, 31, 319581), 'address': 'ssss', 'bathrooms': 0, 'carparks': 0, 'reported_value': 0, 'landarea': 0, 'is_ownership': False, 'updated_at': datetime.datetime(2018, 9, 3, 9, 27, 31, 319590), 'is_rent': False, 'property_id': 0, 'user_id': '43', 'existing_property': False, 'estimated_value': 0, 'is_moneysoft': False, 'property_type': 1, 'use_estimate': False, 'provider_id': 0, 'financial_account_id': 0}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Mon Sep 03 09:27:31.483267 2018] [wsgi:error] [pid 11015:tid 140562241898240] 
[Mon Sep 03 09:41:43.481385 2018] [wsgi:error] [pid 11015:tid 140562199934720] CRITICAL error in logging! (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'level': 'ERROR', 'logged_at': datetime.datetime(2018, 9, 3, 9, 41, 43, 480764), 'logger': 'project.views', 'msg': KeyError('propertyId',), 'source': '/home/puneet/release_2/humaniti/humaniti/property/api/project/views.py:435', 'trace': None}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 09:41:43.481445 2018] [wsgi:error] [pid 11015:tid 140562199934720] ERROR:project.views:'propertyId'
[Mon Sep 03 09:42:37.826623 2018] [wsgi:error] [pid 11016:tid 140562267076352] CRITICAL error in logging! (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logged_at': datetime.datetime(2018, 9, 3, 9, 42, 37, 693646), 'trace': None, 'source': '/home/puneet/release_2/humaniti/humaniti/property/api/project/views.py:435', 'logger': 'project.views', 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 09:42:37.826686 2018] [wsgi:error] [pid 11016:tid 140562267076352] ERROR:project.views:'propertyId'
[Mon Sep 03 09:43:11.323271 2018] [wsgi:error] [pid 11016:tid 140562199934720] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logged_at': datetime.datetime(2018, 9, 3, 9, 42, 37, 693646), 'trace': None, 'source': '/home/puneet/release_2/humaniti/humaniti/property/api/project/views.py:435', 'logger': 'project.views', 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 09:43:11.323337 2018] [wsgi:error] [pid 11016:tid 140562199934720] ERROR:project.views:'propertyId'
[Mon Sep 03 09:43:47.958055 2018] [wsgi:error] [pid 11016:tid 140562258683648] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logged_at': datetime.datetime(2018, 9, 3, 9, 42, 37, 693646), 'trace': None, 'source': '/home/puneet/release_2/humaniti/humaniti/property/api/project/views.py:435', 'logger': 'project.views', 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 09:43:47.958112 2018] [wsgi:error] [pid 11016:tid 140562258683648] ERROR:project.views:'propertyId'
[Mon Sep 03 09:44:02.389017 2018] [wsgi:error] [pid 11015:tid 140562309039872] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'level': 'ERROR', 'logged_at': datetime.datetime(2018, 9, 3, 9, 41, 43, 480764), 'logger': 'project.views', 'msg': KeyError('propertyId',), 'source': '/home/puneet/release_2/humaniti/humaniti/property/api/project/views.py:435', 'trace': None}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 09:44:02.389094 2018] [wsgi:error] [pid 11015:tid 140562309039872] ERROR:project.views:'propertyId'
[Mon Sep 03 09:48:06.399994 2018] [wsgi:error] [pid 11016:tid 140562258683648] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logged_at': datetime.datetime(2018, 9, 3, 9, 42, 37, 693646), 'trace': None, 'source': '/home/puneet/release_2/humaniti/humaniti/property/api/project/views.py:435', 'logger': 'project.views', 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 09:48:06.400060 2018] [wsgi:error] [pid 11016:tid 140562258683648] ERROR:project.views:'propertyId'
[Mon Sep 03 09:49:41.338631 2018] [wsgi:error] [pid 11016:tid 140562283861760] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logged_at': datetime.datetime(2018, 9, 3, 9, 42, 37, 693646), 'trace': None, 'source': '/home/puneet/release_2/humaniti/humaniti/property/api/project/views.py:435', 'logger': 'project.views', 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 09:49:41.338698 2018] [wsgi:error] [pid 11016:tid 140562283861760] ERROR:project.views:'propertyId'
[Mon Sep 03 09:50:02.518589 2018] [wsgi:error] [pid 11015:tid 140562300647168] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'level': 'ERROR', 'logged_at': datetime.datetime(2018, 9, 3, 9, 41, 43, 480764), 'logger': 'project.views', 'msg': KeyError('propertyId',), 'source': '/home/puneet/release_2/humaniti/humaniti/property/api/project/views.py:435', 'trace': None}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 09:50:02.518655 2018] [wsgi:error] [pid 11015:tid 140562300647168] ERROR:project.views:'propertyId'
[Mon Sep 03 09:50:24.349186 2018] [wsgi:error] [pid 11015:tid 140562300647168] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'level': 'ERROR', 'logged_at': datetime.datetime(2018, 9, 3, 9, 41, 43, 480764), 'logger': 'project.views', 'msg': KeyError('propertyId',), 'source': '/home/puneet/release_2/humaniti/humaniti/property/api/project/views.py:435', 'trace': None}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 09:50:24.349260 2018] [wsgi:error] [pid 11015:tid 140562300647168] ERROR:project.views:'propertyId'
[Mon Sep 03 09:51:01.507526 2018] [wsgi:error] [pid 11016:tid 140561406027520] WARNING:server.helpers.ms_register_financial_account:Failed to register account for manju@humaniti.com. 
[Mon Sep 03 09:52:28.554592 2018] [wsgi:error] [pid 11016:tid 140561406027520] WARNING:server.helpers.ms_register_financial_account:Failed to register account for manju@humaniti.com. 
[Mon Sep 03 09:56:47.928592 2018] [wsgi:error] [pid 11016:tid 140561406027520] WARNING:server.helpers.ms_register_financial_account:Failed to register account for 2sep@d.com. 
[Mon Sep 03 09:57:15.311281 2018] [wsgi:error] [pid 11015:tid 140562433521408] refsdffdsfsfdfsdf beyond@humaniti.com None None
[Mon Sep 03 09:57:16.566792 2018] [wsgi:error] [pid 11015:tid 140562433521408] test test&nbsp
[Mon Sep 03 09:57:16.566823 2018] [wsgi:error] [pid 11015:tid 140562433521408] undefined
[Mon Sep 03 09:57:16.566829 2018] [wsgi:error] [pid 11015:tid 140562433521408] 
[Mon Sep 03 09:57:16.566834 2018] [wsgi:error] [pid 11015:tid 140562433521408] Email sent! Message ID:
[Mon Sep 03 09:57:16.566840 2018] [wsgi:error] [pid 11015:tid 140562433521408] 010201659edd6d99-d3984df0-487c-4017-ad3a-17f6e4fc7454-000000
[Mon Sep 03 09:57:36.047329 2018] [wsgi:error] [pid 11016:tid 140561406027520] WARNING:server.helpers.ms_register_financial_account:Failed to register account for manju@humaniti.com. 
[Mon Sep 03 09:58:00.491821 2018] [wsgi:error] [pid 11016:tid 140561406027520] WARNING:server.helpers.ms_register_financial_account:Failed to register account for manju@humaniti.com. 
[Mon Sep 03 09:58:55.552595 2018] [wsgi:error] [pid 11015:tid 140561380833024] WARNING:server.helpers.ms_register_financial_account:Failed to register account for manju@humaniti.com. 
[Mon Sep 03 10:00:24.569413 2018] [wsgi:error] [pid 11016:tid 140562325825280] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:00:24.569454 2018] [wsgi:error] [pid 11016:tid 140562325825280]   """)
[Mon Sep 03 10:00:24.885378 2018] [wsgi:error] [pid 11016:tid 140562191542016] refsdffdsfsfdfsdf beyond@humaniti.com None None
[Mon Sep 03 10:00:26.565477 2018] [wsgi:error] [pid 11016:tid 140562191542016] test my new one&nbsp
[Mon Sep 03 10:00:26.565534 2018] [wsgi:error] [pid 11016:tid 140562191542016] saravanan.rajendran@beyondanalysis.net
[Mon Sep 03 10:00:26.565541 2018] [wsgi:error] [pid 11016:tid 140562191542016] 
[Mon Sep 03 10:00:26.565547 2018] [wsgi:error] [pid 11016:tid 140562191542016] Email sent! Message ID:
[Mon Sep 03 10:00:26.565552 2018] [wsgi:error] [pid 11016:tid 140562191542016] 010201659ee05366-15679ee4-8220-4dc3-91f5-b77c277546ca-000000
[Mon Sep 03 10:01:39.270191 2018] [wsgi:error] [pid 11015:tid 140561380833024] WARNING:server.helpers.ms_register_financial_account:Failed to register account for manju@humaniti.com. 
[Mon Sep 03 10:02:30.022980 2018] [wsgi:error] [pid 11016:tid 140561406027520] WARNING:server.helpers.ms_register_financial_account:Failed to register account for manju@humaniti.com. 
[Mon Sep 03 10:02:49.087286 2018] [mpm_event:notice] [pid 1394:tid 140562567169920] AH00493: SIGUSR1 received.  Doing graceful restart
[Mon Sep 03 10:02:49.092906 2018] [wsgi:warn] [pid 1394:tid 140562567169920] mod_wsgi: Compiled for Python/3.5.1+.
[Mon Sep 03 10:02:49.092915 2018] [wsgi:warn] [pid 1394:tid 140562567169920] mod_wsgi: Runtime using Python/3.5.2.
[Mon Sep 03 10:02:49.092945 2018] [mpm_event:notice] [pid 1394:tid 140562567169920] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/3.5.2 configured -- resuming normal operations
[Mon Sep 03 10:02:49.092949 2018] [core:notice] [pid 1394:tid 140562567169920] AH00094: Command line: '/usr/sbin/apache2'
[Mon Sep 03 10:02:53.485509 2018] [wsgi:error] [pid 13317:tid 140562458699520] Using conig: server.config.DevelopmentConfig
[Mon Sep 03 10:02:54.982832 2018] [wsgi:error] [pid 13317:tid 140562450306816] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:02:54.982866 2018] [wsgi:error] [pid 13317:tid 140562450306816]   """)
[Mon Sep 03 10:03:08.030117 2018] [wsgi:error] [pid 13316:tid 140562425128704] Using conig: server.config.DevelopmentConfig
[Mon Sep 03 10:03:08.882723 2018] [wsgi:error] [pid 13316:tid 140562433521408] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:08.882744 2018] [wsgi:error] [pid 13316:tid 140562433521408]   """)
[Mon Sep 03 10:03:10.296263 2018] [wsgi:error] [pid 13317:tid 140562425128704] Using config: server.config.DevelopmentConfig
[Mon Sep 03 10:03:10.686154 2018] [wsgi:error] [pid 13317:tid 140562416736000] Using congig: project.config.DevelopmentConfig
[Mon Sep 03 10:03:11.161368 2018] [wsgi:error] [pid 13317:tid 140562416736000] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:11.161399 2018] [wsgi:error] [pid 13317:tid 140562416736000]   """)
[Mon Sep 03 10:03:12.144886 2018] [wsgi:error] [pid 13317:tid 140562258683648] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:12.144919 2018] [wsgi:error] [pid 13317:tid 140562258683648]   """)
[Mon Sep 03 10:03:12.904185 2018] [wsgi:error] [pid 13317:tid 140562241898240] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:12.904211 2018] [wsgi:error] [pid 13317:tid 140562241898240]   """)
[Mon Sep 03 10:03:16.517513 2018] [wsgi:error] [pid 13316:tid 140562258683648] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:16.517545 2018] [wsgi:error] [pid 13316:tid 140562258683648]   """)
[Mon Sep 03 10:03:16.698402 2018] [wsgi:error] [pid 13317:tid 140562292254464] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:16.698440 2018] [wsgi:error] [pid 13317:tid 140562292254464]   """)
[Mon Sep 03 10:03:16.719276 2018] [wsgi:error] [pid 13317:tid 140562292254464] Using config: api.config.DevConfig
[Mon Sep 03 10:03:17.473341 2018] [wsgi:error] [pid 13317:tid 140562458699520] Running with :project.server.config.DevelopmentConfig
[Mon Sep 03 10:03:18.039717 2018] [wsgi:error] [pid 13317:tid 140562458699520] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:18.039744 2018] [wsgi:error] [pid 13317:tid 140562458699520]   """)
[Mon Sep 03 10:03:20.567010 2018] [wsgi:error] [pid 13317:tid 140562325825280] Using config: project.config.DevelopmentConfig
[Mon Sep 03 10:03:20.692919 2018] [wsgi:error] [pid 13317:tid 140562325825280] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:20.692940 2018] [wsgi:error] [pid 13317:tid 140562325825280]   """)
[Mon Sep 03 10:03:21.448480 2018] [wsgi:error] [pid 13317:tid 140562275469056] wsdlpath /usr/local/lib/python3.5/dist-packages/confirmit-0.1-py3.5.egg/confirmit
[Mon Sep 03 10:03:23.523226 2018] [wsgi:error] [pid 13317:tid 140562275469056] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:23.523256 2018] [wsgi:error] [pid 13317:tid 140562275469056]   """)
[Mon Sep 03 10:03:23.770290 2018] [wsgi:error] [pid 13316:tid 140562233505536] Running with :project.server.config.DevelopmentConfig
[Mon Sep 03 10:03:24.022692 2018] [wsgi:error] [pid 13317:tid 140562208327424] Using config: api.config.DevelopmentConfig
[Mon Sep 03 10:03:24.298723 2018] [wsgi:error] [pid 13316:tid 140562233505536] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:24.298747 2018] [wsgi:error] [pid 13316:tid 140562233505536]   """)
[Mon Sep 03 10:03:24.626195 2018] [wsgi:error] [pid 13317:tid 140562183149312] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:24.626209 2018] [wsgi:error] [pid 13317:tid 140562183149312]   """)
[Mon Sep 03 10:03:33.177458 2018] [wsgi:error] [pid 13316:tid 140562325825280] Using config: project.config.DevelopmentConfig
[Mon Sep 03 10:03:33.304056 2018] [wsgi:error] [pid 13316:tid 140562325825280] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:33.304079 2018] [wsgi:error] [pid 13316:tid 140562325825280]   """)
[Mon Sep 03 10:03:41.251000 2018] [wsgi:error] [pid 13316:tid 140562283861760] Using config: api.config.DevelopmentConfig
[Mon Sep 03 10:03:41.493137 2018] [wsgi:error] [pid 13316:tid 140562241898240] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:41.493155 2018] [wsgi:error] [pid 13316:tid 140562241898240]   """)
[Mon Sep 03 10:03:44.393078 2018] [wsgi:error] [pid 13316:tid 140562225112832] Using congig: project.config.DevelopmentConfig
[Mon Sep 03 10:03:44.897837 2018] [wsgi:error] [pid 13316:tid 140562225112832] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:44.897861 2018] [wsgi:error] [pid 13316:tid 140562225112832]   """)
[Mon Sep 03 10:03:47.590201 2018] [wsgi:error] [pid 13316:tid 140562216720128] ERROR:project.views:(psycopg2.IntegrityError) duplicate key value violates unique constraint "user_property_uc"
[Mon Sep 03 10:03:47.590232 2018] [wsgi:error] [pid 13316:tid 140562216720128] DETAIL:  Key (user_id, address)=(13, 1-164, Singannnapalem, Mundlamuru, Prakasam, Andhrapradesh, India) already exists.
[Mon Sep 03 10:03:47.590238 2018] [wsgi:error] [pid 13316:tid 140562216720128]  [SQL: 'INSERT INTO property (user_id, is_ownership, is_rent, rent_amount, property_id, address, property_type, bedrooms, carparks, bathrooms, landarea, estimated_value, financial_account_id, reported_value, existing_property, use_estimate, provider_id, is_moneysoft, created_at, updated_at) VALUES (%(user_id)s, %(is_ownership)s, %(is_rent)s, %(rent_amount)s, %(property_id)s, %(address)s, %(property_type)s, %(bedrooms)s, %(carparks)s, %(bathrooms)s, %(landarea)s, %(estimated_value)s, %(financial_account_id)s, %(reported_value)s, %(existing_property)s, %(use_estimate)s, %(provider_id)s, %(is_moneysoft)s, %(created_at)s, %(updated_at)s) RETURNING property.id'] [parameters: {'bathrooms': 34, 'estimated_value': 343, 'created_at': datetime.datetime(2018, 9, 3, 10, 3, 47, 414459), 'property_type': 1, 'is_moneysoft': False, 'bedrooms': 4545, 'use_estimate': False, 'existing_property': True, 'address': '1-164, Singannnapalem, Mundlamuru, Prakasam, Andhrapradesh, India', 'financial_account_id': 0, 'provider_id': 0, 'rent_amount': 0, 'carparks': 4545, 'is_ownership': False, 'updated_at': datetime.datetime(2018, 9, 3, 10, 3, 47, 414469), 'reported_value': 0, 'landarea': 323, 'user_id': '13', 'is_rent': False, 'property_id': 0}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Mon Sep 03 10:03:47.590248 2018] [wsgi:error] [pid 13316:tid 140562216720128] 
[Mon Sep 03 10:03:59.661597 2018] [wsgi:error] [pid 13316:tid 140562225112832] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:03:59.661620 2018] [wsgi:error] [pid 13316:tid 140562225112832]   """)
[Mon Sep 03 10:03:59.666151 2018] [wsgi:error] [pid 13316:tid 140562225112832] Using config: api.config.DevConfig
[Mon Sep 03 10:04:07.786250 2018] [wsgi:error] [pid 13316:tid 140562267076352] Using config: server.config.DevelopmentConfig
[Mon Sep 03 10:04:08.151999 2018] [wsgi:error] [pid 13316:tid 140562334217984] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:04:08.152040 2018] [wsgi:error] [pid 13316:tid 140562334217984]   """)
[Mon Sep 03 10:04:26.467750 2018] [wsgi:error] [pid 13316:tid 140562241898240] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:04:26.467782 2018] [wsgi:error] [pid 13316:tid 140562241898240]   """)
[Mon Sep 03 10:16:06.171840 2018] [wsgi:error] [pid 13316:tid 140562199934720] wsdlpath /usr/local/lib/python3.5/dist-packages/confirmit-0.1-py3.5.egg/confirmit
[Mon Sep 03 10:16:08.243325 2018] [wsgi:error] [pid 13316:tid 140562199934720] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:16:08.243357 2018] [wsgi:error] [pid 13316:tid 140562199934720]   """)
[Mon Sep 03 10:19:14.114236 2018] [wsgi:error] [pid 13317:tid 140562199934720] Using config: project.config.DevelopmentConfig
[Mon Sep 03 10:19:14.495324 2018] [wsgi:error] [pid 13317:tid 140562199934720] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:19:14.495346 2018] [wsgi:error] [pid 13317:tid 140562199934720]   """)
[Mon Sep 03 10:21:48.819767 2018] [wsgi:error] [pid 13317:tid 140561425426176] WARNING:server.helpers.ms_register_financial_account:Failed to register account for manju@humaniti.com. 
[Mon Sep 03 10:22:34.601820 2018] [wsgi:error] [pid 13316:tid 140562309039872] Using config: project.config.DevelopmentConfig
[Mon Sep 03 10:22:34.972031 2018] [wsgi:error] [pid 13316:tid 140562309039872] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 10:22:34.972055 2018] [wsgi:error] [pid 13316:tid 140562309039872]   """)
[Mon Sep 03 10:23:02.462212 2018] [wsgi:error] [pid 13317:tid 140562250290944] ERROR:project.views:Authorization header attribute missing
[Mon Sep 03 10:24:48.020010 2018] [wsgi:error] [pid 13317:tid 140562433521408] ERROR:project.views:Authorization header attribute missing
[Mon Sep 03 10:26:06.442662 2018] [wsgi:error] [pid 13317:tid 140561425426176] WARNING:server.helpers.ms_register_financial_account:Failed to register account for 2sep@d.com. 
[Mon Sep 03 10:27:16.673787 2018] [wsgi:error] [pid 13316:tid 140562317432576] [client 121.244.36.135:53552] mod_wsgi (pid=13316): Exception occurred processing WSGI script '/home/suraj/humloyalty/humaniti/humaniti/financial/api/financial.wsgi'., referer: http://localhost:4200/accounts/link-account?textField=retyer&passwordField=reytreyt&option=yes
[Mon Sep 03 10:27:16.673948 2018] [wsgi:error] [pid 13316:tid 140562317432576] [client 121.244.36.135:53552] OSError: failed to write data, referer: http://localhost:4200/accounts/link-account?textField=retyer&passwordField=reytreyt&option=yes
[Mon Sep 03 10:27:18.359513 2018] [wsgi:error] [pid 13316:tid 140562309039872] [client 121.244.36.135:53541] mod_wsgi (pid=13316): Exception occurred processing WSGI script '/home/suraj/humloyalty/humaniti/humaniti/financial/api/financial.wsgi'., referer: http://localhost:4200/accounts/link-account
[Mon Sep 03 10:27:18.359667 2018] [wsgi:error] [pid 13316:tid 140562309039872] [client 121.244.36.135:53541] OSError: failed to write data, referer: http://localhost:4200/accounts/link-account
[Mon Sep 03 10:27:36.257438 2018] [wsgi:error] [pid 13317:tid 140562225112832] [client 203.145.182.245:53612] mod_wsgi (pid=13317): Exception occurred processing WSGI script '/home/suraj/humloyalty/humaniti/humaniti/financial/api/financial.wsgi'., referer: http://localhost:4200/accounts/link-account?textField=retyer&passwordField=reytreyt&option=yes
[Mon Sep 03 10:27:36.257589 2018] [wsgi:error] [pid 13317:tid 140562225112832] [client 203.145.182.245:53612] OSError: failed to write data, referer: http://localhost:4200/accounts/link-account?textField=retyer&passwordField=reytreyt&option=yes
[Mon Sep 03 10:29:35.278470 2018] [wsgi:error] [pid 13316:tid 140562225112832] [client 121.244.36.135:53908] mod_wsgi (pid=13316): Exception occurred processing WSGI script '/home/suraj/humloyalty/humaniti/humaniti/financial/api/financial.wsgi'., referer: http://localhost:4200/accounts/link-account?textField=retyer&passwordField=reytreyt&option=yes
[Mon Sep 03 10:29:35.278619 2018] [wsgi:error] [pid 13316:tid 140562225112832] [client 121.244.36.135:53908] OSError: failed to write data, referer: http://localhost:4200/accounts/link-account?textField=retyer&passwordField=reytreyt&option=yes
[Mon Sep 03 10:32:37.909975 2018] [wsgi:error] [pid 13316:tid 140562416736000] [client 203.145.182.245:53602] mod_wsgi (pid=13316): Exception occurred processing WSGI script '/home/suraj/humloyalty/humaniti/humaniti/financial/api/financial.wsgi'., referer: http://localhost:4200/accounts/link-account
[Mon Sep 03 10:32:37.910129 2018] [wsgi:error] [pid 13316:tid 140562416736000] [client 203.145.182.245:53602] OSError: failed to write data, referer: http://localhost:4200/accounts/link-account
[Mon Sep 03 10:36:34.134993 2018] [wsgi:error] [pid 13316:tid 140562233505536] CRITICAL error in logging! (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'msg': KeyError('propertyId',), 'logger': 'project.views', 'trace': None, 'logged_at': datetime.datetime(2018, 9, 3, 10, 36, 34, 134386), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR'}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 10:36:34.135056 2018] [wsgi:error] [pid 13316:tid 140562233505536] ERROR:project.views:'propertyId'
[Mon Sep 03 10:37:49.565717 2018] [wsgi:error] [pid 13317:tid 140562191542016] CRITICAL error in logging! (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'msg': KeyError('propertyId',), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'logged_at': datetime.datetime(2018, 9, 3, 10, 37, 49, 565096), 'logger': 'project.views', 'trace': None, 'level': 'ERROR'}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 10:37:49.565777 2018] [wsgi:error] [pid 13317:tid 140562191542016] ERROR:project.views:'propertyId'
[Mon Sep 03 10:39:11.943076 2018] [wsgi:error] [pid 13316:tid 140562183149312] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'msg': KeyError('propertyId',), 'logger': 'project.views', 'trace': None, 'logged_at': datetime.datetime(2018, 9, 3, 10, 36, 34, 134386), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR'}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 10:39:11.943165 2018] [wsgi:error] [pid 13316:tid 140562183149312] ERROR:project.views:'propertyId'
[Mon Sep 03 10:40:47.012781 2018] [wsgi:error] [pid 13316:tid 140562267076352] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'msg': KeyError('propertyId',), 'logger': 'project.views', 'trace': None, 'logged_at': datetime.datetime(2018, 9, 3, 10, 36, 34, 134386), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR'}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 10:40:47.012844 2018] [wsgi:error] [pid 13316:tid 140562267076352] ERROR:project.views:'propertyId'
[Mon Sep 03 10:41:35.686655 2018] [wsgi:error] [pid 13316:tid 140562416736000] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'msg': KeyError('propertyId',), 'logger': 'project.views', 'trace': None, 'logged_at': datetime.datetime(2018, 9, 3, 10, 36, 34, 134386), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR'}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 10:41:35.686720 2018] [wsgi:error] [pid 13316:tid 140562416736000] ERROR:project.views:'propertyId'
[Mon Sep 03 10:44:35.939380 2018] [wsgi:error] [pid 13317:tid 140562267076352] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'msg': KeyError('propertyId',), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'logged_at': datetime.datetime(2018, 9, 3, 10, 37, 49, 565096), 'logger': 'project.views', 'trace': None, 'level': 'ERROR'}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 10:44:35.939447 2018] [wsgi:error] [pid 13317:tid 140562267076352] ERROR:project.views:'propertyId'
[Mon Sep 03 11:08:16.244685 2018] [wsgi:error] [pid 13317:tid 140562267076352] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'msg': KeyError('propertyId',), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'logged_at': datetime.datetime(2018, 9, 3, 10, 37, 49, 565096), 'logger': 'project.views', 'trace': None, 'level': 'ERROR'}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:08:16.244760 2018] [wsgi:error] [pid 13317:tid 140562267076352] ERROR:project.views:(psycopg2.IntegrityError) duplicate key value violates unique constraint "user_property_uc"
[Mon Sep 03 11:08:16.244766 2018] [wsgi:error] [pid 13317:tid 140562267076352] DETAIL:  Key (user_id, address)=(13, PANAMPUNNA) already exists.
[Mon Sep 03 11:08:16.244770 2018] [wsgi:error] [pid 13317:tid 140562267076352]  [SQL: 'INSERT INTO property (user_id, is_ownership, is_rent, rent_amount, property_id, address, property_type, bedrooms, carparks, bathrooms, landarea, estimated_value, financial_account_id, reported_value, existing_property, use_estimate, provider_id, is_moneysoft, created_at, updated_at) VALUES (%(user_id)s, %(is_ownership)s, %(is_rent)s, %(rent_amount)s, %(property_id)s, %(address)s, %(property_type)s, %(bedrooms)s, %(carparks)s, %(bathrooms)s, %(landarea)s, %(estimated_value)s, %(financial_account_id)s, %(reported_value)s, %(existing_property)s, %(use_estimate)s, %(provider_id)s, %(is_moneysoft)s, %(created_at)s, %(updated_at)s) RETURNING property.id'] [parameters: {'property_type': 1, 'existing_property': False, 'is_ownership': False, 'use_estimate': False, 'estimated_value': 0, 'provider_id': 0, 'bathrooms': 0, 'carparks': 0, 'user_id': '13', 'rent_amount': 0, 'created_at': datetime.datetime(2018, 9, 3, 11, 8, 16, 240759), 'property_id': 0, 'bedrooms': 0, 'updated_at': datetime.datetime(2018, 9, 3, 11, 8, 16, 240767), 'reported_value': 0, 'financial_account_id': 0, 'landarea': 0, 'is_moneysoft': False, 'address': 'PANAMPUNNA', 'is_rent': False}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Mon Sep 03 11:08:16.244776 2018] [wsgi:error] [pid 13317:tid 140562267076352] 
[Mon Sep 03 11:09:09.164112 2018] [wsgi:error] [pid 13317:tid 140562183149312] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'msg': KeyError('propertyId',), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'logged_at': datetime.datetime(2018, 9, 3, 10, 37, 49, 565096), 'logger': 'project.views', 'trace': None, 'level': 'ERROR'}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:09:09.164177 2018] [wsgi:error] [pid 13317:tid 140562183149312] ERROR:project.views:(psycopg2.IntegrityError) duplicate key value violates unique constraint "user_property_uc"
[Mon Sep 03 11:09:09.164184 2018] [wsgi:error] [pid 13317:tid 140562183149312] DETAIL:  Key (user_id, address)=(13, 36 DERRY STREET GANMAIN NSW 2702) already exists.
[Mon Sep 03 11:09:09.164188 2018] [wsgi:error] [pid 13317:tid 140562183149312]  [SQL: 'INSERT INTO property (user_id, is_ownership, is_rent, rent_amount, property_id, address, property_type, bedrooms, carparks, bathrooms, landarea, estimated_value, financial_account_id, reported_value, existing_property, use_estimate, provider_id, is_moneysoft, created_at, updated_at) VALUES (%(user_id)s, %(is_ownership)s, %(is_rent)s, %(rent_amount)s, %(property_id)s, %(address)s, %(property_type)s, %(bedrooms)s, %(carparks)s, %(bathrooms)s, %(landarea)s, %(estimated_value)s, %(financial_account_id)s, %(reported_value)s, %(existing_property)s, %(use_estimate)s, %(provider_id)s, %(is_moneysoft)s, %(created_at)s, %(updated_at)s) RETURNING property.id'] [parameters: {'property_type': 1, 'existing_property': False, 'is_ownership': False, 'use_estimate': False, 'estimated_value': 0, 'provider_id': 0, 'bathrooms': 0, 'carparks': 0, 'user_id': '13', 'rent_amount': 0, 'created_at': datetime.datetime(2018, 9, 3, 11, 9, 9, 160924), 'property_id': 0, 'bedrooms': 0, 'updated_at': datetime.datetime(2018, 9, 3, 11, 9, 9, 160932), 'reported_value': 0, 'financial_account_id': 0, 'landarea': 0, 'is_moneysoft': False, 'address': '36 DERRY STREET GANMAIN NSW 2702', 'is_rent': False}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Mon Sep 03 11:09:09.164205 2018] [wsgi:error] [pid 13317:tid 140562183149312] 
[Mon Sep 03 11:12:24.102107 2018] [wsgi:error] [pid 13317:tid 140561425426176] WARNING:server.helpers.ms_register_financial_account:Failed to register account for 3sep@d.com. 
[Mon Sep 03 11:14:01.697199 2018] [wsgi:error] [pid 13316:tid 140562250290944] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'msg': KeyError('propertyId',), 'logger': 'project.views', 'trace': None, 'logged_at': datetime.datetime(2018, 9, 3, 10, 36, 34, 134386), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR'}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:14:01.697267 2018] [wsgi:error] [pid 13316:tid 140562250290944] ERROR:project.views:'propertyId'
[Mon Sep 03 11:17:00.815679 2018] [wsgi:error] [pid 13316:tid 140562233505536] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'msg': KeyError('propertyId',), 'logger': 'project.views', 'trace': None, 'logged_at': datetime.datetime(2018, 9, 3, 10, 36, 34, 134386), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR'}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:17:00.815737 2018] [wsgi:error] [pid 13316:tid 140562233505536] ERROR:project.views:'propertyId'
[Mon Sep 03 11:18:12.449575 2018] [wsgi:error] [pid 13317:tid 140562191542016] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'msg': KeyError('propertyId',), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'logged_at': datetime.datetime(2018, 9, 3, 10, 37, 49, 565096), 'logger': 'project.views', 'trace': None, 'level': 'ERROR'}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:18:12.449641 2018] [wsgi:error] [pid 13317:tid 140562191542016] ERROR:project.views:'propertyId'
[Mon Sep 03 11:21:24.040221 2018] [core:warn] [pid 1394:tid 140562567169920] AH00045: child process 13316 still did not exit, sending a SIGTERM
[Mon Sep 03 11:21:24.040274 2018] [core:warn] [pid 1394:tid 140562567169920] AH00045: child process 13317 still did not exit, sending a SIGTERM
[Mon Sep 03 11:21:26.042473 2018] [mpm_event:notice] [pid 1394:tid 140562567169920] AH00491: caught SIGTERM, shutting down
[Mon Sep 03 11:21:26.827663 2018] [wsgi:warn] [pid 13919:tid 140640853624704] mod_wsgi: Compiled for Python/3.5.1+.
[Mon Sep 03 11:21:26.827702 2018] [wsgi:warn] [pid 13919:tid 140640853624704] mod_wsgi: Runtime using Python/3.5.2.
[Mon Sep 03 11:21:26.828177 2018] [mpm_event:notice] [pid 13919:tid 140640853624704] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/3.5.2 configured -- resuming normal operations
[Mon Sep 03 11:21:26.828202 2018] [core:notice] [pid 13919:tid 140640853624704] AH00094: Command line: '/usr/sbin/apache2'
[Mon Sep 03 11:21:27.862584 2018] [wsgi:error] [pid 13923:tid 140640745154304] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:21:27.862622 2018] [wsgi:error] [pid 13923:tid 140640745154304]   """)
[Mon Sep 03 11:21:27.873966 2018] [wsgi:error] [pid 13923:tid 140640745154304] Using config: api.config.DevConfig
[Mon Sep 03 11:21:28.000076 2018] [wsgi:error] [pid 13922:tid 140640641869568] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:21:28.000110 2018] [wsgi:error] [pid 13922:tid 140640641869568]   """)
[Mon Sep 03 11:21:28.004779 2018] [wsgi:error] [pid 13922:tid 140640641869568] Using config: api.config.DevConfig
[Mon Sep 03 11:21:33.865018 2018] [wsgi:error] [pid 13923:tid 140640728368896] Using config: server.config.DevelopmentConfig
[Mon Sep 03 11:21:34.139413 2018] [wsgi:error] [pid 13922:tid 140640633476864] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:21:34.139441 2018] [wsgi:error] [pid 13922:tid 140640633476864]   """)
[Mon Sep 03 11:21:34.361253 2018] [wsgi:error] [pid 13923:tid 140640474015488] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:21:34.361282 2018] [wsgi:error] [pid 13923:tid 140640474015488]   """)
[Mon Sep 03 11:21:34.706278 2018] [wsgi:error] [pid 13922:tid 140640625084160] Using congig: project.config.DevelopmentConfig
[Mon Sep 03 11:21:35.083820 2018] [wsgi:error] [pid 13922:tid 140640625084160] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:21:35.083851 2018] [wsgi:error] [pid 13922:tid 140640625084160]   """)
[Mon Sep 03 11:21:35.878449 2018] [wsgi:error] [pid 13923:tid 140640608298752] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:21:35.878480 2018] [wsgi:error] [pid 13923:tid 140640608298752]   """)
[Mon Sep 03 11:21:37.109295 2018] [wsgi:error] [pid 13923:tid 140640599906048] Running with :project.server.config.DevelopmentConfig
[Mon Sep 03 11:21:37.377188 2018] [wsgi:error] [pid 13923:tid 140640599906048] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:21:37.377218 2018] [wsgi:error] [pid 13923:tid 140640599906048]   """)
[Mon Sep 03 11:21:43.586581 2018] [wsgi:error] [pid 13922:tid 140640557942528] Using config: api.config.DevelopmentConfig
[Mon Sep 03 11:21:43.835955 2018] [wsgi:error] [pid 13922:tid 140640541157120] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:21:43.835974 2018] [wsgi:error] [pid 13922:tid 140640541157120]   """)
[Mon Sep 03 11:21:44.358175 2018] [wsgi:error] [pid 13922:tid 140640532764416] CRITICAL error in logging! (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:21:44.358251 2018] [wsgi:error] [pid 13922:tid 140640532764416] ERROR:project.views:'propertyId'
[Mon Sep 03 11:21:56.059249 2018] [wsgi:error] [pid 13923:tid 140640591513344] Using conig: server.config.DevelopmentConfig
[Mon Sep 03 11:21:56.867950 2018] [wsgi:error] [pid 13923:tid 140640591513344] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:21:56.867973 2018] [wsgi:error] [pid 13923:tid 140640591513344]   """)
[Mon Sep 03 11:22:31.489733 2018] [wsgi:error] [pid 13922:tid 140640524371712] Using conig: server.config.DevelopmentConfig
[Mon Sep 03 11:22:32.205126 2018] [wsgi:error] [pid 13922:tid 140640515979008] Using config: server.config.DevelopmentConfig
[Mon Sep 03 11:22:32.365245 2018] [wsgi:error] [pid 13922:tid 140640745154304] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:22:32.365260 2018] [wsgi:error] [pid 13922:tid 140640745154304]   """)
[Mon Sep 03 11:22:32.581592 2018] [wsgi:error] [pid 13922:tid 140640641869568] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:22:32.581612 2018] [wsgi:error] [pid 13922:tid 140640641869568]   """)
[Mon Sep 03 11:22:42.539733 2018] [wsgi:error] [pid 13923:tid 140640583120640] Using config: api.config.DevelopmentConfig
[Mon Sep 03 11:22:42.794253 2018] [wsgi:error] [pid 13923:tid 140640566335232] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:22:42.794280 2018] [wsgi:error] [pid 13923:tid 140640566335232]   """)
[Mon Sep 03 11:22:43.010202 2018] [wsgi:error] [pid 13922:tid 140640625084160] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:22:43.010264 2018] [wsgi:error] [pid 13922:tid 140640625084160] ERROR:project.views:'propertyId'
[Mon Sep 03 11:24:42.018309 2018] [wsgi:error] [pid 13923:tid 140640499193600] Using congig: project.config.DevelopmentConfig
[Mon Sep 03 11:24:42.389351 2018] [wsgi:error] [pid 13923:tid 140640499193600] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:24:42.389373 2018] [wsgi:error] [pid 13923:tid 140640499193600]   """)
[Mon Sep 03 11:24:43.254520 2018] [wsgi:error] [pid 13923:tid 140640482408192] CRITICAL error in logging! (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logger': 'project.views', 'logged_at': datetime.datetime(2018, 9, 3, 11, 24, 43, 238066), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'trace': None, 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:24:43.254586 2018] [wsgi:error] [pid 13923:tid 140640482408192] ERROR:project.views:'propertyId'
[Mon Sep 03 11:25:09.570091 2018] [wsgi:error] [pid 13922:tid 140640566335232] Running with :project.server.config.DevelopmentConfig
[Mon Sep 03 11:25:09.839364 2018] [wsgi:error] [pid 13922:tid 140640566335232] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:25:09.839386 2018] [wsgi:error] [pid 13922:tid 140640566335232]   """)
[Mon Sep 03 11:25:13.356568 2018] [wsgi:error] [pid 13922:tid 140640736761600] Using config: project.config.DevelopmentConfig
[Mon Sep 03 11:25:13.646103 2018] [wsgi:error] [pid 13922:tid 140640736761600] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:25:13.646125 2018] [wsgi:error] [pid 13922:tid 140640736761600]   """)
[Mon Sep 03 11:25:50.509528 2018] [wsgi:error] [pid 13923:tid 140640728368896] Using config: project.config.DevelopmentConfig
[Mon Sep 03 11:25:50.637763 2018] [wsgi:error] [pid 13923:tid 140640728368896] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:25:50.637795 2018] [wsgi:error] [pid 13923:tid 140640728368896]   """)
[Mon Sep 03 11:25:55.073947 2018] [wsgi:error] [pid 13922:tid 140640541157120] wsdlpath /usr/local/lib/python3.5/dist-packages/confirmit-0.1-py3.5.egg/confirmit
[Mon Sep 03 11:25:57.027472 2018] [wsgi:error] [pid 13922:tid 140640541157120] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:25:57.027500 2018] [wsgi:error] [pid 13922:tid 140640541157120]   """)
[Mon Sep 03 11:27:15.425901 2018] [wsgi:error] [pid 13922:tid 140640549549824] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:27:15.425970 2018] [wsgi:error] [pid 13922:tid 140640549549824] ERROR:project.views:'propertyId'
[Mon Sep 03 11:27:58.898369 2018] [wsgi:error] [pid 13922:tid 140640608298752] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:27:58.898427 2018] [wsgi:error] [pid 13922:tid 140640608298752] ERROR:project.views:'propertyId'
[Mon Sep 03 11:29:48.091358 2018] [wsgi:error] [pid 13923:tid 140640474015488] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logger': 'project.views', 'logged_at': datetime.datetime(2018, 9, 3, 11, 24, 43, 238066), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'trace': None, 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:29:48.091431 2018] [wsgi:error] [pid 13923:tid 140640474015488] ERROR:project.views:'propertyId'
[Mon Sep 03 11:32:09.319827 2018] [wsgi:error] [pid 13922:tid 140640499193600] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:32:09.319893 2018] [wsgi:error] [pid 13922:tid 140640499193600] ERROR:project.views:'propertyId'
[Mon Sep 03 11:34:52.701392 2018] [wsgi:error] [pid 13923:tid 140640574727936] wsdlpath /usr/local/lib/python3.5/dist-packages/confirmit-0.1-py3.5.egg/confirmit
[Mon Sep 03 11:34:54.733341 2018] [wsgi:error] [pid 13923:tid 140640574727936] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 11:34:54.733371 2018] [wsgi:error] [pid 13923:tid 140640574727936]   """)
[Mon Sep 03 11:37:52.527081 2018] [wsgi:error] [pid 13923:tid 140640566335232] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logger': 'project.views', 'logged_at': datetime.datetime(2018, 9, 3, 11, 24, 43, 238066), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'trace': None, 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:37:52.527170 2018] [wsgi:error] [pid 13923:tid 140640566335232] ERROR:project.views:'propertyId'
[Mon Sep 03 11:38:49.052543 2018] [wsgi:error] [pid 13922:tid 140640641869568] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:38:49.052609 2018] [wsgi:error] [pid 13922:tid 140640641869568] ERROR:project.views:Authorization header attribute missing
[Mon Sep 03 11:46:36.708922 2018] [wsgi:error] [pid 13923:tid 140640515979008] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logger': 'project.views', 'logged_at': datetime.datetime(2018, 9, 3, 11, 24, 43, 238066), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'trace': None, 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:46:36.708996 2018] [wsgi:error] [pid 13923:tid 140640515979008] ERROR:project.views:'propertyId'
[Mon Sep 03 11:46:40.565275 2018] [wsgi:error] [pid 13923:tid 140640499193600] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logger': 'project.views', 'logged_at': datetime.datetime(2018, 9, 3, 11, 24, 43, 238066), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'trace': None, 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:46:40.565328 2018] [wsgi:error] [pid 13923:tid 140640499193600] ERROR:project.views:'propertyId'
[Mon Sep 03 11:48:18.689501 2018] [wsgi:error] [pid 13923:tid 140640650262272] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logger': 'project.views', 'logged_at': datetime.datetime(2018, 9, 3, 11, 24, 43, 238066), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'trace': None, 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:48:18.689567 2018] [wsgi:error] [pid 13923:tid 140640650262272] ERROR:project.views:Authorization header attribute missing
[Mon Sep 03 11:51:48.430756 2018] [wsgi:error] [pid 13922:tid 140640507586304] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:51:48.430825 2018] [wsgi:error] [pid 13922:tid 140640507586304] ERROR:project.views:Authorization header attribute missing
[Mon Sep 03 11:53:17.638349 2018] [wsgi:error] [pid 13922:tid 140640474015488] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:53:17.638425 2018] [wsgi:error] [pid 13922:tid 140640474015488] ERROR:project.views:Authorization header attribute missing
[Mon Sep 03 11:53:25.398577 2018] [wsgi:error] [pid 13923:tid 140640490800896] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logger': 'project.views', 'logged_at': datetime.datetime(2018, 9, 3, 11, 24, 43, 238066), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'trace': None, 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:53:25.398641 2018] [wsgi:error] [pid 13923:tid 140640490800896] ERROR:project.views:Authorization header attribute missing
[Mon Sep 03 11:54:00.315779 2018] [wsgi:error] [pid 13922:tid 140640616691456] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:54:00.315851 2018] [wsgi:error] [pid 13922:tid 140640616691456] ERROR:project.views:Authorization header attribute missing
[Mon Sep 03 11:55:05.328535 2018] [wsgi:error] [pid 13923:tid 140640474015488] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'logger': 'project.views', 'logged_at': datetime.datetime(2018, 9, 3, 11, 24, 43, 238066), 'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'trace': None, 'level': 'ERROR', 'msg': KeyError('propertyId',)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:55:05.328602 2018] [wsgi:error] [pid 13923:tid 140640474015488] ERROR:project.views:'NoneType' object is not subscriptable
[Mon Sep 03 11:55:47.812795 2018] [wsgi:error] [pid 13922:tid 140640574727936] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 11:55:47.812858 2018] [wsgi:error] [pid 13922:tid 140640574727936] ERROR:project.views:'NoneType' object is not subscriptable
[Mon Sep 03 12:08:41.321919 2018] [wsgi:error] [pid 13922:tid 140640557942528] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 12:08:41.322002 2018] [wsgi:error] [pid 13922:tid 140640557942528] ERROR:project.views:'propertyId'
[Mon Sep 03 12:31:25.056506 2018] [wsgi:error] [pid 13922:tid 140640736761600] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 12:31:25.056572 2018] [wsgi:error] [pid 13922:tid 140640736761600] ERROR:project.views:'propertyId'
[Mon Sep 03 14:22:46.218103 2018] [wsgi:error] [pid 13922:tid 140640541157120] CRITICAL error in logging! This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'KeyError' [SQL: 'INSERT INTO logs (logger, level, source, trace, msg, logged_at) VALUES (%(logger)s, %(level)s, %(source)s, %(trace)s, %(msg)s, %(logged_at)s) RETURNING logs.id'] [parameters: {'source': '/home/suraj/humloyalty/humaniti/humaniti/property/api/project/views.py:435', 'level': 'ERROR', 'trace': None, 'logger': 'project.views', 'msg': KeyError('propertyId',), 'logged_at': datetime.datetime(2018, 9, 3, 11, 21, 44, 338058)}] (Background on this error at: http://sqlalche.me/e/f405)
[Mon Sep 03 14:22:46.218166 2018] [wsgi:error] [pid 13922:tid 140640541157120] ERROR:project.views:(psycopg2.IntegrityError) duplicate key value violates unique constraint "user_property_uc"
[Mon Sep 03 14:22:46.218171 2018] [wsgi:error] [pid 13922:tid 140640541157120] DETAIL:  Key (user_id, address)=(34, 28 SYDNEYR STREET MORTLAKE NSW 2137) already exists.
[Mon Sep 03 14:22:46.218176 2018] [wsgi:error] [pid 13922:tid 140640541157120]  [SQL: 'INSERT INTO property (user_id, is_ownership, is_rent, rent_amount, property_id, address, property_type, bedrooms, carparks, bathrooms, landarea, estimated_value, financial_account_id, reported_value, existing_property, use_estimate, provider_id, is_moneysoft, created_at, updated_at) VALUES (%(user_id)s, %(is_ownership)s, %(is_rent)s, %(rent_amount)s, %(property_id)s, %(address)s, %(property_type)s, %(bedrooms)s, %(carparks)s, %(bathrooms)s, %(landarea)s, %(estimated_value)s, %(financial_account_id)s, %(reported_value)s, %(existing_property)s, %(use_estimate)s, %(provider_id)s, %(is_moneysoft)s, %(created_at)s, %(updated_at)s) RETURNING property.id'] [parameters: {'carparks': 2, 'use_estimate': True, 'landarea': 543, 'existing_property': True, 'bathrooms': 1, 'rent_amount': 0, 'user_id': '34', 'address': '28 SYDNEYR STREET MORTLAKE NSW 2137', 'property_id': 0, 'created_at': datetime.datetime(2018, 9, 3, 14, 22, 46, 214996), 'is_moneysoft': True, 'is_rent': False, 'provider_id': 0, 'reported_value': 0, 'property_type': 1, 'is_ownership': False, 'updated_at': datetime.datetime(2018, 9, 3, 14, 22, 46, 215003), 'bedrooms': 4, 'financial_account_id': 0, 'estimated_value': 1893338}] (Background on this error at: http://sqlalche.me/e/gkpj)
[Mon Sep 03 14:22:46.218193 2018] [wsgi:error] [pid 13922:tid 140640541157120] 
[Mon Sep 03 14:24:54.237194 2018] [wsgi:error] [pid 14404:tid 140640625084160] Using congig: project.config.DevelopmentConfig
[Mon Sep 03 14:24:54.638696 2018] [wsgi:error] [pid 14404:tid 140640625084160] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 14:24:54.638716 2018] [wsgi:error] [pid 14404:tid 140640625084160]   """)
[Mon Sep 03 14:25:11.904907 2018] [wsgi:error] [pid 14404:tid 140640608298752] Using config: api.config.DevelopmentConfig
[Mon Sep 03 14:25:12.707791 2018] [wsgi:error] [pid 14404:tid 140640599906048] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 14:25:12.707816 2018] [wsgi:error] [pid 14404:tid 140640599906048]   """)
[Mon Sep 03 14:27:51.746478 2018] [wsgi:error] [pid 14404:tid 140640625084160] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 14:27:51.746512 2018] [wsgi:error] [pid 14404:tid 140640625084160]   """)
[Mon Sep 03 14:30:44.610464 2018] [wsgi:error] [pid 14404:tid 140640549549824] Using config: project.config.DevelopmentConfig
[Mon Sep 03 14:30:44.846644 2018] [wsgi:error] [pid 14404:tid 140640549549824] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 14:30:44.846665 2018] [wsgi:error] [pid 14404:tid 140640549549824]   """)
[Mon Sep 03 14:30:45.104206 2018] [wsgi:error] [pid 14404:tid 140640532764416] Using config: server.config.DevelopmentConfig
[Mon Sep 03 14:30:45.602954 2018] [wsgi:error] [pid 14404:tid 140640515979008] Using conig: server.config.DevelopmentConfig
[Mon Sep 03 14:30:46.019200 2018] [wsgi:error] [pid 14404:tid 140640515979008] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 14:30:46.019228 2018] [wsgi:error] [pid 14404:tid 140640515979008]   """)
[Mon Sep 03 14:30:46.410808 2018] [wsgi:error] [pid 14404:tid 140640499193600] Running with :project.server.config.DevelopmentConfig
[Mon Sep 03 14:30:46.681092 2018] [wsgi:error] [pid 14404:tid 140640499193600] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 14:30:46.681125 2018] [wsgi:error] [pid 14404:tid 140640499193600]   """)
[Mon Sep 03 14:30:46.849064 2018] [wsgi:error] [pid 14404:tid 140640728368896] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 14:30:46.849080 2018] [wsgi:error] [pid 14404:tid 140640728368896]   """)
[Mon Sep 03 14:30:47.596583 2018] [wsgi:error] [pid 14404:tid 140640490800896] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Mon Sep 03 14:30:47.596612 2018] [wsgi:error] [pid 14404:tid 140640490800896]   """)
[Mon Sep 03 14:30:47.602448 2018] [wsgi:error] [pid 14404:tid 140640490800896] Using config: api.config.DevConfig
[Mon Sep 03 15:06:20.503441 2018] [wsgi:error] [pid 14404:tid 140639756089088] WARNING:server.helpers.ms_register_financial_account:No financial institution found for id: 49
[Mon Sep 03 15:06:20.506355 2018] [wsgi:error] [pid 14404:tid 140639756089088] ERROR:server.helpers.ms_register_financial_account:'NoneType' object has no attribute 'users'
[Mon Sep 03 15:06:20.506365 2018] [wsgi:error] [pid 14404:tid 140639756089088] Traceback (most recent call last):
[Mon Sep 03 15:06:20.506368 2018] [wsgi:error] [pid 14404:tid 140639756089088]   File "/home/suraj/humloyalty/humaniti/humaniti/financial/api/server/helpers/ms_register_financial_account.py", line 80, in update_db
[Mon Sep 03 15:06:20.506371 2018] [wsgi:error] [pid 14404:tid 140639756089088]     inst.users.append(usr)
[Mon Sep 03 15:06:20.506374 2018] [wsgi:error] [pid 14404:tid 140639756089088] AttributeError: 'NoneType' object has no attribute 'users'
[Mon Sep 03 15:06:20.506379 2018] [wsgi:error] [pid 14404:tid 140639756089088] 
[Tue Sep 04 04:29:16.340300 2018] [wsgi:error] [pid 14404:tid 140640499193600] Using config: project.config.DevelopmentConfig
[Tue Sep 04 04:29:16.711838 2018] [wsgi:error] [pid 14404:tid 140640499193600] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Tue Sep 04 04:29:16.711856 2018] [wsgi:error] [pid 14404:tid 140640499193600]   """)
[Tue Sep 04 05:52:46.318202 2018] [wsgi:error] [pid 14404:tid 140640616691456] wsdlpath /usr/local/lib/python3.5/dist-packages/confirmit-0.1-py3.5.egg/confirmit
[Tue Sep 04 05:52:48.299381 2018] [wsgi:error] [pid 14404:tid 140640616691456] /usr/local/lib/python3.5/dist-packages/psycopg2-2.7.5-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Tue Sep 04 05:52:48.299410 2018] [wsgi:error] [pid 14404:tid 140640616691456]   """)
[Tue Sep 04 06:25:02.001974 2018] [mpm_event:notice] [pid 13919:tid 140640853624704] AH00493: SIGUSR1 received.  Doing graceful restart
Exception ignored in: <function _ConnectionRecord.checkout.<locals>.<lambda> at 0x7fe93df8ef28>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 545, in <lambda>
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 719, in _finalize_fairy
NameError: name 'BaseException' is not defined
